pipeline:
  name: test
  identifier: test
  projectIdentifier: handalin
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: gittama
        repoName: coba15092023
        build: <+input>
  stages:
    - stage:
        name: nambah repo baru
        identifier: nambah_repo_baru
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: Run_1
                  identifier: Run_1
                  spec:
                    shell: Sh
                    command: ip addr
    - stage:
        name: masuk key
        identifier: masuk_key
        description: ""
        type: Deployment
        spec:
          deploymentType: Kubernetes
          service:
            serviceRef: javaapp
          environment:
            environmentRef: key
            deployToAll: false
            infrastructureDefinitions:
              - identifier: key
          execution:
            steps:
              - step:
                  name: Rollout Deployment
                  identifier: rolloutDeployment
                  type: K8sRollingDeploy
                  timeout: 10m
                  spec:
                    skipDryRun: false
                    pruningEnabled: false
            rollbackSteps:
              - step:
                  name: Rollback Rollout Deployment
                  identifier: rollbackRolloutDeployment
                  type: K8sRollingRollback
                  timeout: 10m
                  spec:
                    pruningEnabled: false
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
